### PR TITLE
Fix uma transparent bug on damage

### LINKED ISSUE #1566: [BUG] Uma keeps a red color after attack
## 🐛 Bug Report

https://github.com/lambdaclass/curse_of_mirra/assets/82987608/c19a2f01-55d8-4a91-a9c3-fa10303765f2

### Steps to Reproduce

- start a match with one other player and uma
- have the other player attack uma just when she activates her ulti 
- Uma will stay red after she reappears until another attack is dealt to her

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1566 

## Motivation

Fix uma invisible texture bug on damage

## Summary of changes

- Redue the calls of `HandleInvisible` method in CharacterFeedbackManager
- Change the alpha of the overlay colors depending if the character is invisible or not.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by AngieDutra — DISMISSED** [review]
Tested with both Unity desktop and Android build in a match with both characters being Uma:
- Umas attacking each other while using their Ulti
- Umas watching each other enter the kill zone while using the Ulti
Everything worked as expected ✨

**Comment by AngieDutra** [comment]
I see my approve on this got revoked. I'll re-review now 😊

**Review by AngieDutra — DISMISSED** [review]
Tested on Unity desktop and Android build. Worked great!

**Comment by AngieDutra** [comment]
Since my review was dismissed due to a recent merge I'll review again ✨

**Review by AngieDutra — APPROVED** [review]
Re-tested it and worked great! ✨

**Review by agustinesco — APPROVED** [review]
LGTM! tested on both an android build and the unity client and the uma invisibility is fixed! i've noticed that the errors is also happening when i hit uma while she is invisible and this pr also fixes that! nice

**Pull request merged**
