### PR TITLE
Shake and Fash effect on damage

### LINKED ISSUE #1264: [FEATURE] Screen shake when receiving damage
## 🚀 Feature
Implement camera shaking effect upon receiving damage.

### Specifications
- Add a camera shake animation triggered when the player character receives damage.
- The intensity and duration of the camera shake should be adjustable for optimal user experience.
- There could be also a super fast flashing effect (red or white).

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1264 

## Motivation

Implement shake and flash feedback when receiving damage.

## Summary of changes

1. Created DamageFeedback prefab
2. Created `DamageFeedback` Method and wrap others damage feedbacks inside it (Haptic and Texture) in `CharacterFeedbacks` script 
3. Added DamageFeedback prefab to CharacterFeedback.cs `feedbackPrefabs` list.

## How has this been tested?

Start a new game, when you receive damage you should notice a little screen shake and screen flash

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.

### CODE REVIEW

**Review by ncontinanza — DISMISSED** [review]
LGTM! Tested locally and on an Android device, everything worked great.

**Review by agustinesco — CHANGES_REQUESTED** [review]
Great changes! i tested them both in the unity client and in an andriod build and it worked as a charm, i just have one concern, when i get the first hit the screen is shaking but an exception is appearing in the unity console, should we fix it?

**Comment by BertovDev** [comment]
> Great changes! i tested them both in the unity client and in an andriod build and it worked as a charm, i just have one concern, when i get the first hit the screen is shaking but an exception is appearing in the unity console, should we fix it?

Can you provide a image of the ecxeption?

**Comment by agustinesco** [comment]
> > Great changes! i tested them both in the unity client and in an andriod build and it worked as a charm, i just have one concern, when i get the first hit the screen is shaking but an exception is appearing in the unity console, should we fix it?
> 
> Can you provide a image of the ecxeption?

sure thing

image

**Review by ncontinanza — APPROVED** [review]

**Review by agustinesco — APPROVED** [review]
Looking good!

**Pull request merged**
