### PR TITLE
Disappear souls in Uma

### LINKED ISSUE #1524: [BUG] Uma fires not disapearing when she casts his ultimate
## 🐛 Bug Report

When uma uses his ultimate she is suposed to turn invisible but the fires near her are not dissapearing

### Steps to Reproduce

Ult with uma, to do so on the browser do this:
- Start a match with the unity client 
- Go to [This](http://localhost:3000/board/1/uma) url on you browser
- Ult using the key "o" on you browser

#### Screenshot

https://github.com/lambdaclass/curse_of_mirra/assets/106101218/108eea44-8bb8-4c9a-8b4c-9ba4e0232421

### Your Environment

Main

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1524 

## Motivation

Souls was not disappearing in Uma ultimate

## Summary of changes

Add a list of vfx to disappear if the characters allow invisibility

Disclaimer: I could not use MMCondition with the list to display only if the character has vfx to disappear. 

## How has this been tested?

Select 2 uma, the enemy should disappear complety. Your uma no changes should be displayed.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Tested this with Unity desktop and my Android mobile. Seems it's not working. I saw the vfx and it's empty. Maybe because of that?
Captura de pantalla 2024-03-07 a la(s) 11 44 00

**Comment by BertovDev** [comment]
> Tested this with Unity desktop and my Android mobile. Seems it's not working. I saw the vfx and it's empty. Maybe because of that? Captura de pantalla 2024-03-07 a la(s) 11 44 00

Yep, the list is empty. Nice catch

**Review by AngieDutra — APPROVED** [review]
Tested on Unity desktop and Android build ✨

**Review by agustinesco — APPROVED** [review]
LGTM!

**Pull request merged**
