### PR TITLE
[GH-1703] Add winner to death splash

### LINKED ISSUE #1703: [FEATURE] Add winner in death Splash
## 🚀 Feature

- Add winner to death Splash
- When the match ends we should add the winner of the match.

Reference and Assets
https://drive.google.com/drive/folders/1d67wZjnBIys0IXFhp8m7iWdieNze9kkl

### PR DESCRIPTION
**Pull request by alfopisano**
Closes #1703

## Motivation
We need to show the winner of the battle on the death splash 

## Summary of changes
- Added the winner container following the given reference 
- Added the functionality to show the actual winner 

Reference: 
reference-winner

Result: 
Screenshot 2024-04-29 at 09 14 47

Important: I did not touch the rank container so the differences between it and the reference are already existing on main

## How has this been tested?
Tested on iOS build

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by jazimp** [comment]
Looks good! The only thing missing is the shadow on the number:
Implementation vs design
Captura de pantalla 2024-04-26 a la(s) 17 15 52
Captura de pantalla 2024-04-26 a la(s) 17 16 08

**Comment by alfopisano** [comment]
> Looks good! The only thing missing is the shadow on the number: Implementation vs design Captura de pantalla 2024-04-26 a la(s) 17 15 52 Captura de pantalla 2024-04-26 a la(s) 17 16 08

Oh you are right!! Must have deleted it when doing some changes because I remember adding it, on it.

**Comment by jazimp** [comment]
Looks great! 😄

**Review by AngieDutra — APPROVED** [review]
✔️ Assets correctly imported in Unity
✔️ Playtested with Unity desktop and Android build
✔️ Checked multiple cases included the fact there is no winner yet but I get to the death splash sooner than that. I like the transition added in the component there @alfopisano, great touch

**Pull request merged**
