### PR TITLE
Fixed Muflus' Roll animator flow

### LINKED ISSUE #1620: [BUG] Broken Muflus animation on roll
## 🐛 Bug Report
Sometimes, if you continue moving after rolling, the animation stays in the rolling state until you stop moving.
This happens mostly due to high latency or connectivity issues.

### PR DESCRIPTION
**Pull request by saugon**
Closes #1620 

## Motivation
Sometimes, if you continue moving after rolling, the animation stayed in the rolling state until you stopped moving.

## Summary of changes

- Fixed Muflus' animator flow.

## How has this been tested?
- Playing in a distant server to force the conditions that lead to the error.
- Executing a roll while moving, the animation shouldn't get stuck.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by AngieDutra** [comment]
Nice! I'll review this now

**Comment by BertovDev** [comment]
Reviewing this

**Review by AngieDutra — COMMENTED** [review]
Are we using "MuflusController" or should we delete this?
Captura de pantalla 2024-03-21 a la(s) 4 05 40 p  m

**Comment by saugon** [comment]
> Are we using "MuflusController" or should we delete this? Captura de pantalla 2024-03-21 a la(s) 4 05 40 p  m

Not in this PR, we have to clean up some other things too related to this.

**Review by BertovDev — APPROVED** [review]

**Review by AngieDutra — APPROVED** [review]
Awesome!

**Pull request merged**
