### PR TITLE
New valtimer vfx

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #[issue]

## Motivation

The shader of antimatter is broken

There is one texture that is not working in Iphone  so it was removed. more info in this issue https://github.com/lambdaclass/curse_of_mirra/issues/1506

Reference:

https://drive.google.com/drive/u/0/folders/1ihV9yxG4QOS6E20cOwLNtEQ7kO7NxBnJ

## Summary of changes

List changes in code.

## How has this been tested?

Enable valtimer in CharactersManager. then test the vfx are looking good.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by agustinesco — CHANGES_REQUESTED** [review]
I got a few comments about the valtimer animations:
- Basic: the vfx doesn't seem to be timed with the valtimer animation, also are we using the correct animation?
- Ultimate: It seems good, we will be able to move the pool to a different position once it's implemented on the backend right?
- dash: The portal that the dash open it's not at the point where valtimer is supposed to spawn, is this waiting on the backend implementation?

https://github.com/lambdaclass/curse_of_mirra/assets/106101218/2e91bbb3-03cd-4110-a833-a67593e33794

**Comment by BertovDev** [comment]
> I got a few comments about the valtimer animations:
> 
>     * Basic: the vfx doesn't seem to be timed with the valtimer animation, also are we using the correct animation?
> 
>     * Ultimate: It seems good, we will be able to move the pool to a different position once it's implemented on the backend right?
> 
>     * dash: The portal that the dash open it's not at the point where valtimer is supposed to spawn, is this waiting on the backend implementation?
> 
> 
> Screen.Recording.2024-02-26.at.12.52.45.mov

The syncs between animations and vfx are not made, since i will implemented correctly in each ability iteration. In this PR check that the vfx are looking good and correctly in comparative with the reference. And the animations working good in the animator inspector.

**Review by agustinesco — DISMISSED** [review]
LGTM! even tho the animation are not being completed on the game they seems to be good on the animation inspector of unity

**Comment by AngieDutra** [comment]
> LGTM! even tho the animation are not being completed on the game they seems to be good on the animation inspector of unity

I'm not sure if this PR as it is should be in main taking into account the user can see the animations not working with the timing as it should. Will check this with the team and come back to update what is decided

**Review by AngieDutra — APPROVED** [review]
LGTM ✨

**Review by agustinesco — APPROVED** [review]
LGTM! tested the pr with an android build and it works perfect!

**Pull request merged**
