### PR TITLE
Update defeat screen

### LINKED ISSUE #1457: [FEATURE] Update win/defeat screen
## 🚀 Feature

- Update the assets with the new color palette.

### Assets

https://drive.google.com/drive/folders/1sXvQomDqcO2NwPdhtzq6U_7qglZkGmWP?usp=drive_link

### References
defeated-ref
reference-win

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1457 

## Motivation

Update win / defeat screen with new assets

## Summary of changes

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by AngieDutra — CHANGES_REQUESTED** [review]
The background image is missing it's reference
Captura de pantalla 2024-02-26 a las 11 54 11 a  m
Captura de pantalla 2024-02-26 a las 11 47 17 a  m

**Review by AngieDutra — COMMENTED** [review]
Also, make sure the following files are correctly commited
Captura de pantalla 2024-02-26 a las 11 59 35 a  m

**Review by AngieDutra — COMMENTED** [review]
Tested the defeated screen and seems like for the first seconds the character model kind of falls down into place and then the animation starts. If you think this is an issue for another PR I'll create the issue but I believe it's best to solve it here so the endgame screen is ready

**Comment by BertovDev** [comment]
> Tested the defeated screen and seems like for the first seconds the character model kind of falls down into place and then the animation starts. If you think this is an issue for another PR I'll create the issue but I believe it's best to solve it here so the endgame screen is ready

I will upload the change to fix this. Nice catch

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Everything is looking good. Small change to be made: There are still assets from the previous design. Adding new assets in folders called "new" or "assets" is tricky. I recommend for ui implementations this is good as long as after that all the previous files are deleted and the new files are taken out of that folder created and after emptying it that folder is deleted

**Review by AngieDutra — CHANGES_REQUESTED** [review]
I believe you deleted an in-use asset. if you need any help let me know
Captura de pantalla 2024-02-27 a la(s) 14 03 22

**Review by AngieDutra — APPROVED** [review]

**Review by agustinesco — APPROVED** [review]
LGTM! tested in both the unity client and an android build and everything worked fine!

**Pull request merged**
