### PR TITLE
Prepare for battle cinematic fix

### LINKED ISSUE #1384: [BUG] Fix prepare for battle camera
## 🐛 Bug Report

After the new changes in the backend about the initial position, the prepare for battle camera movement is bugged.

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1384 

## Motivation

With the integrations of the players initial position the cinematic got broken

## Summary of changes

The fix was to replace the front end player position with the back end position since they initially spawn and then move to the back end position.

## How has this been tested?

Start a game and it should look smooth again

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by BertovDev — APPROVED** [review]
LGTM

**Comment by lotuuu** [comment]
How is the cinematic broken in main? I couldn't find any differences between this PR and the main branch

**Comment by BertovDev** [comment]
> How is the cinematic broken in main? I couldn't find any differences between this PR and the main branch

In some cases the camera is a little bit offset from the player and then pans to it

**Comment by AngieDutra** [comment]
> How is the cinematic broken in main? I couldn't find any differences between this PR and the main branch

The cinematic should be one movement and instead when it focuses on the player it kind of snaps from it's last position

**Review by lotuuu — APPROVED** [review]

**Pull request merged**
