### PR TITLE
Natural Healing feedback

### LINKED ISSUE #959: [FEATURE] Implement natural healing
## 🚀 Feature

The characters will periodically heal part of their health. 

Implementation:
- Characters heal 10% of their health per second
- The healing is interrupted for (config: 3000ms) after using an ability or being struck
- For VFX we can use the current healing anim

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #959 

## Motivation

The characters in main are missing some natural healing feedbacks

## Summary of changes

This PR adds natural healing feedbacks

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by AngieDutra** [comment]
> I don't think the stars in the end of the feedback are very aligned with the look and feel of the game, and I also feel that it is too much information. I think that the health bar + the lines that go towards the character are perfect, but I think I would remove the stars https://github.com/lambdaclass/curse_of_mirra/assets/22064054/7d6b6deb-83a6-41bc-b7ca-1c7ef835442e

Agree. Like them but if they feel off I'll delete them

**Comment by mgrunwaldt** [comment]
> > I don't think the stars in the end of the feedback are very aligned with the look and feel of the game, and I also feel that it is too much information. I think that the health bar + the lines that go towards the character are perfect, but I think I would remove the stars https://github.com/lambdaclass/curse_of_mirra/assets/22064054/7d6b6deb-83a6-41bc-b7ca-1c7ef835442e
> 
> Agree. Like them but if they feel off I'll delete them

delete them and we'll see how it looks

**Review by mgrunwaldt — APPROVED** [review]
LGTM!

**Review by BertovDev — APPROVED** [review]
Tested on Android S23 working fine!

**Review by manucamejo — APPROVED** [review]

**Pull request merged**
