### PR TITLE
Save selected character on client

### PR DESCRIPTION
**Pull request by BertovDev**
## Motivation

Minor QoL improvement, save character name in the client after selected

## Summary of changes

- Save the character name in the playerPrefs
- If not null selected the character save or Muflus for default.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by agustinesco — CHANGES_REQUESTED** [review]
image

i can't start the game :C

**Comment by BertovDev** [comment]
> image
> 
> i can't start the game :C

Done! test it if you have a moment.

**Review by agustinesco — APPROVED** [review]
Nice!

**Review by AngieDutra — APPROVED** [review]
Awesome!

**Pull request merged**
