### PR TITLE
Restore sprite to button

### PR DESCRIPTION
**Pull request by AngieDutra**
## Motivation

Set player name pop up "save" button was missing its sprite

## Summary of changes

This PR restores it

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by BertovDev** [comment]
To test it you can in the `TtitleScreenController.cs` line 48 change the `PlayerPrefs.GetString("playerName") == "" `condition to `PlayerPrefs.GetString("playerName") != ""`

**Review by BertovDev — APPROVED** [review]

**Comment by lotuuu** [comment]
Screen Shot 2024-02-06 at 15 58 09

It looks the same to me on main and on this branch

**Review by lotuuu — APPROVED** [review]
Only after switching to a different branch did the save button appear broken again, probably some dark Unity magic. Works fine then!

**Comment by AngieDutra** [comment]
> Screen Shot 2024-02-06 at 15 58 09
> It looks the same to me on main and on this branch
Captura de pantalla 2024-02-06 a la(s) 16 04 26
This is how it looks in main. Maybe try closing and reopening Unity

**Pull request merged**
