### PR TITLE
Select server QoL

### PR DESCRIPTION
**Pull request by BertovDev**
## Motivation

Add server selection depending if it is a mobile build or the unity editor.

## How has this been tested?

Make a build, Brasil should be selected as server and when playing in the PC localhost should be selected.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by AngieDutra** [comment]
Nice! I'll review now

**Review by AngieDutra — APPROVED** [review]
This PR needs main merged to have the fonts working as expected.

✔️  Tested with Unity desktop and default server is Localhost
✔️  Tested on Android build and default server is Brazil

**Comment by agustinesco** [comment]
Reviewing

**Review by agustinesco — APPROVED** [review]
LGTM!

**Pull request merged**
