### PR TITLE
Add sand storm

### LINKED ISSUE #1550: [FEATURE] Add sand storm vfx
## 🚀 Feature

Isolate Sand Storm from new-zone-vfx and added it in a different PR.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1550 

## Motivation

Add sand storm vfx to araban map

## Summary of changes

Add sand storm prefab with vfx.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by AngieDutra — COMMENTED** [review]
It's not looking as high quality as it could. It glitches from time to time too. I'm using an Android

**Review by agustinesco — APPROVED** [review]
LGTM! tested in both the unity client and in an android build at the same time and it's looking good! i didn't find any glitch or visual error

one small observation:
you can see the sand coming out of the wall on this point


https://github.com/lambdaclass/curse_of_mirra/assets/106101218/c506fd5a-c7ba-4a72-9315-c70c4d69e500

**Review by AngieDutra — APPROVED** [review]
Tested merging main and in IOS device

**Comment by AngieDutra** [comment]
I'll create an issue with @agustinesco 's observation to track this

**Pull request merged**
