### PR TITLE
[GH-1599] Create feature to change players name

### LINKED ISSUE #1599: [FEATURE] Change Player Name
## 🚀 Feature

Crate a Change name option in Main Screen settings.

- As soon as the Main screen settings is add create a GameObject to change you playerName.

### PR DESCRIPTION
**Pull request by alfopisano**
Closes #1599

## Motivation
We need a way to change the player's name since once selected when playing for the first time there is no way of modifying it. 

## Summary of changes
Added a new section on the game's settings from the main screen where you can change the player's name. Here the game selector will be displayed and the user would be able to select a new name. 

[allow to change players name on main screen](https://github.com/lambdaclass/curse_of_mirra/pull/1661/commits/7b61a43a17128dccbb7a90cac57686777753c8fb)

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by BertovDev — APPROVED** [review]
Really nice!! I was about to comment the thing about the scene but now I see you already fixed it so awesome.

**Comment by agustinesco** [comment]
just to comment it , i think we should only display a button called "change player name" here instead of a legend explaining it 

image

**Review by agustinesco — APPROVED** [review]
LGTM!

**Review by BertovDev — APPROVED** [review]
Awesome!

**Review by agustinesco — APPROVED** [review]
Niiiceeeeee

**Review by BertovDev — APPROVED** [review]
LGTM!!

**Pull request merged**
