### PR TITLE
Enable uma

### PR DESCRIPTION
**Pull request by manucamejo**
- [x] Enable Uma

We need to link Uma's animations correctly.

### CODE REVIEW

**Review by BertovDev — DISMISSED** [review]
LGTM

**Comment by AngieDutra** [comment]
Did this [PR](https://github.com/lambdaclass/curse_of_mirra/pull/1412) to fix the animation bugs

**Review by mgrunwaldt — DISMISSED** [review]

**Comment by BertovDev** [comment]
Looking good and just a comment. Uma Scaling and position in game are not correct. I believe it will be better to have this fix in another PR so we can move on this. But to have in mind I leave the reference.

Screenshot 2024-02-08 at 11 01 25
Screenshot 2024-02-08 at 11 00 53

**Comment by AngieDutra** [comment]
> Looking good and just a comment. Uma Scaling and position in game are not correct. I believe it will be better to have this fix in another PR so we can move on this. But to have in mind I leave the reference.
> 
> Screenshot 2024-02-08 at 11 01 25 Screenshot 2024-02-08 at 11 00 53

I can fix scaling but not positioning since the model's anchors are all different. It will look good in one direction but wron in the other if I were to move them. Another PR on this would be aproppiate since it would be a refactor. I created issue [1414](https://github.com/lambdaclass/curse_of_mirra/issues/1414) for that
Captura de pantalla 2024-02-08 a la(s) 19 59 07
Captura de pantalla 2024-02-08 a la(s) 19 58 25

**Review by BertovDev — APPROVED** [review]

**Comment by AngieDutra** [comment]
If this [PR](https://github.com/lambdaclass/curse_of_mirra/pull/1410) is merged before this one, Uma's in game prefab needs to be updated

**Review by mgrunwaldt — APPROVED** [review]

**Pull request merged**
