### PR TITLE
Add cooldowns back

### LINKED ISSUE #1594: [FEATURE] Add back cooldowns
## 🚀 Feature
This feature should be developed based on https://github.com/lambdaclass/mirra_backend/pull/378.

The goal is to add back cooldown to the skills that have that mechanism.

- Prevent the triggering of a skill if the cooldown is still in progress.
- Show the cooldown timer on top of the skill button.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1594 

Test with -> https://github.com/lambdaclass/mirra_backend/pull/378
## Motivation

Add  cooldowns back to skill2 and skill3.

## Summary of changes

Get each skill cooldown and use it in the CustominputManager `CheckSkillCooldown` method.

## How has this been tested?

Check basic with stamina usage and skill2 and skill3 with cooldowns.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by saugon — DISMISSED** [review]
👌🏻

**Review by AngieDutra — CHANGES_REQUESTED** [review]
I think you may be missing the cooldown bool value in each skill's scriptable object. It should be tru for the cooldowns to show. If this bool is no longer wanted since we use backend data we can just delete the values in that regard (cooldown bool and float)
Captura de pantalla 2024-03-17 a la(s) 11 35 57 p  m

**Comment by BertovDev** [comment]
> I think you may be missing the cooldown bool value in each skill's scriptable object. It should be tru for the cooldowns to show. If this bool is no longer wanted since we use backend data we can just delete the values in that regard (cooldown bool and float) Captura de pantalla 2024-03-17 a la(s) 11 35 57 p  m

Nice! I did not realize I did not pushed it.

**Comment by BertovDev** [comment]
https://github.com/lambdaclass/curse_of_mirra/issues/1599

**Review by agustinesco — APPROVED** [review]
LGTM! tested on both android and the unity client and worked like a charm

**Pull request merged**
