### PR TITLE
[Gh-1746] Quick game

### LINKED ISSUE #1746: [FEATURE] Quick game button
## 🚀 Feature

We want a quick game button for development purposes. It should go straight to battle in a match with the client user and bots

### Motivation

Quick Game reference

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1746

## Motivation

We need a quick game button to improve development speed

## Summary of changes

This PR:
- Adds quick game button
- Fixes the store button orientation
- Refactors a bit how we handle the scene changes

Screenshot 2024-05-07 at 12 34 03

The refactor's design is the following:
- Added in Utils all the server logic regarding the creation of the game
- I created a script called "GameNavigation" which contains all the methods regarding the game creation and exit of it. These methods where not only repeated though the same scene like in battle (exit in settings and death splash), but now they can be used at any instance of the game such as a near future matchmaking cancel button or in one scene with different types of creating a match
- Then I left each scene manager with methods and logics that will only be used in those scenes such as: 
  - MainManager the go to character list and the model handling
  - CharacterListManager for the list generation
  - CharacterInfoManager for the selection of the character

In the future, the ultimate goal would be to do the game navigation through code and avoid references in the scene. However, if this was done in this PR it would also requiere a refactor in the button component used in all the UI across the game so I believed it was best to iterate on that

## How has this been tested?

Use both play and quick game buttons. Play should work the same as main. Quick game should send you instantly to battle with just the client player and bots

## Checklist
- [x] I have tested the changes locally.
- [x] I have tested the whole game after applying the changes, not only the affected areas.
- [x] I self-reviewed the changes on GitHub, line by line.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [x] Tested in Android.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by AngieDutra** [comment]
I'll fix a change server issue

**Comment by jazimp** [comment]
Looks good! It has my visual approval! ✅

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on iOS build and everything seemed to work as expected

**Review by tvillegas98 — APPROVED** [review]
Seems to work well and the refactor looks good!

**Pull request merged**
