### PR TITLE
Refactor SendPlayerMovement method in Battle.cs

### LINKED ISSUE #1406: [BUG] Characters continue moving after death
## 🐛 Bug Report

Sometimes invisible or looking as clouds.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes  #1406

## Motivation

Various method in Battle.cs can we improved. This is one of them.

## Summary of changes

- Remove unused variables inside the method
- Simplify `playerControls` getComponent call to 1
- GetCharacter instead of GameObject.

## How has this been tested?

Game should be working as always.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by AngieDutra — DISMISSED** [review]
Nice one

**Review by AngieDutra — APPROVED** [review]
Tested it turning client prediction off and worked fine!

**Comment by lotuuu** [comment]
https://github.com/lambdaclass/curse_of_mirra/assets/31993243/d658cd31-38a2-431f-bb07-9c7dfc07470d

Not working for me. Do I need tu use a backend branch different than main?

**Comment by BertovDev** [comment]
> Screen.Recording.2024-02-06.at.16.46.26.mov
> 
> Not working for me. Do I need tu use a backend branch different than main?

I am currently using main and everything seems to be working fine.

**Comment by BertovDev** [comment]
The strange thing is that it happens only sometimes. But mostly is working fine

**Review by lotuuu — APPROVED** [review]
Now movement is working fine! I'm assuming skill animations are not working because this doesn't have the latest main changes merged in

**Comment by BertovDev** [comment]
> Now movement is working fine! I'm assuming skill animations are not working because this doesn't have the latest main changes merged in

Nice. What i did in this last commit was:

Instead of assigning the character in the Start when sometimes the `GetCharacter` returns null  (Because the list of players still empty for that frame)  I am doing it once inside the `SendPlayerMovement` method when everything is already set correctly.

**Review by AngieDutra — APPROVED** [review]
Nice work!

**Pull request merged**
