### PR TITLE
Camera reposition

### LINKED ISSUE #957: [FEATURE] Camera reposition
## 🚀 Feature
Let’s zoom the camera out a little and adjust the angle, so that the player has more vision and therefore information about the match and can plan a strategy for their next move. Check reference.

### PR DESCRIPTION
**Pull request by saugon**
Closes #957 

## Motivation
To provide players with more visibility and information about the match, and therefore helping them plan their strategies, we slightly moved the camera away.

## Summary of changes
- Changed the camera distance from the player.

## References
⚠️ Disclaimer: ignore the broken timer in the match stats info.

**Before**
Screenshot 2024-03-13 at 19 43 00
**After**
Screenshot 2024-03-13 at 19 43 16

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by BertovDev** [comment]
Do we want to merge this with the Araban map background like this?
Screenshot 2024-03-15 at 10 07 11

**Comment by saugon** [comment]
> Do we want to merge this with the Araban map background like this? Screenshot 2024-03-15 at 10 07 11

Not really, thanks! Fixed

**Comment by AngieDutra** [comment]
Awesome! Will review it now ✨

**Review by BertovDev — APPROVED** [review]
Looking good now!

**Review by AngieDutra — APPROVED** [review]
Tested on Unity desktop and Android build and is looking awesome!

**Pull request merged**
