### PR TITLE
[GH-1682] Quests mockup

### PR DESCRIPTION
**Pull request by alfopisano**
Issue #1682 

## Motivation
This PR is the first part for the Quests screen. Here all components were created but none of them has functionality. That would be added on further iterations. 

## Summary of changes
Created the new Quests scene and its components. 

## How has this been tested?
Just go to the Quests section and take a look at it. 

The Quests screen: 
Screenshot 2024-04-24 at 16 37 43

The design: 
Screenshot 2024-04-19 at 12 48 47

-> Although the "REROLL" button looks different, checked with Jaz and it is the secondary button (the one I used) 

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by mgrunwaldt** [comment]
@alfopisano it could be nice if for PRs that involve UI you include a screenshot of what you made (this PR has this) and under it a screenshot of the original design, so it is easy to compare, plus the link to the original design

**Review by BertovDev — COMMENTED** [review]
This is looking really nice and does this also includes the responsive design ? Because in the moment I change to others screen it looks broken.

**Comment by alfopisano** [comment]
> This is looking really nice and does this also includes the responsive design ? Because in the moment I change to others screen it looks broken.

What do you mean with others screen?

**Comment by alfopisano** [comment]
After talking to Gonza I will be making some changes to polish it ✨

**Review by AngieDutra — CHANGES_REQUESTED** [review]
I love the slider idea in this implementation!
Implementations could be improved and would solve a lot of issues that show in the asstes and fonts. Also the assets config isn'r right. Take into account:
- Small assets are imported in 512 max size
- Button images are not set as sliced but as simple
- Avoid scaling images in only one value (x,y,z). If scaling changes should only be because a native size was applied and the scale should change in all axis the same amount to preserv resolution
- Ideally, images with point corners should be set to avoid braking on with or heigh change. Set those correctly or use the simple hack of setting to nativa size and rescaling.
- Use the copying reference hack I showed you to make sure the implementation is accurate to the reference
- Careful with text implementation. Check the extra settings margins are not modifies by accident
- There are no .5 values in font size. Try to set round values in the font sizes inputs

**Review by AngieDutra — CHANGES_REQUESTED** [review]
Screenshot 2024-04-24 at 17 22 31

Talked with the design team and decided the following:
Quest should actually be quests
The soon label should be re added there until the hole section is done and available for users
Therefore, the link in this button to the quest section should be deleted also. To avoid having some "soon" labeled buttons that allow the user to enter a new scene and some that don't

**Review by AngieDutra — APPROVED** [review]
LGTM! Awesome PR

**Comment by jazimp** [comment]
Good job! I'm leaving this ticket with adjustments to add when implementing functionality https://github.com/lambdaclass/curse_of_mirra/issues/1727

**Review by BertovDev — APPROVED** [review]

**Pull request merged**
