### PR TITLE
Added delay parameters for each vfx of Uma's Avenge skill

### LINKED ISSUE #1628: [FEATURE] Parameterize Uma's basic vfx
## 🚀 Feature
Parameterize the execution delay of Uma's basic vfx.

### PR DESCRIPTION
**Pull request by saugon**
Closes #1628 

## Motivation
We needed to modify Uma's Avenge VFXs delay to match the animation.

## Summary of changes

Added 4 new properties to handle each swing vfx delay.

## How has this been tested?

Changing these properties values should cause the VFXs to spawn accordingly.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by BertovDev** [comment]
Reviewing

**Review by BertovDev — APPROVED** [review]
Nice!

**Comment by BertovDev** [comment]
Maybe we should wait until https://github.com/lambdaclass/mirra_backend/pull/398 is merge, since it change the animation speed of Uma basic and due to that you should change the vfx delay values in this PR

**Comment by AngieDutra** [comment]
I'll wait to approve this PR until there is a final decision on this

**Comment by AngieDutra** [comment]
Reviewing now ✨

**Review by AngieDutra — APPROVED** [review]
Tested in Android build and Unity desktop

**Pull request merged**
