### PR TITLE
Server popup update styles

### LINKED ISSUE #1448: [FEATURE] Update design and implementation Servers Pop-up
### Assets
 Pop up:
 https://drive.google.com/drive/folders/1n2msMu7JfeYrweJfVIy6SHPZf0E8_YyF?usp=drive_link
 
Buttons:
https://drive.google.com/drive/folders/1h93h0kjVentkQGeoLqCXmc7HB0Y7pBGr?usp=drive_link

### References
refe
refe 1

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1448 

## Motivation

The server selection pop up was outdated and the us server option should be deleted as the default server

## Summary of changes
DENVER'S server was requested to be removed so this image is outdated. Now the default server is Brazil.

Reference:
server pop-up

Implementation:
Captura de pantalla 2024-03-05 a las 12 01 00 p  m

In addition:
- Fixed implementation of shadows for text mesh pro so we avoid some current issues in that regard (different spacing for lack of automatization, centering text issues and duplicated texts)

## How has this been tested?

- Check the custom option with an ngrok
- Test each server selection works
- Go through every screen and splash to check the text's shadows look good
- Have a close look at the button animations in the server selection splash since I also fixed those (some buttons had a wrong anchor and the scale animation was not centered

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.

### CODE REVIEW

**Review by Nico-Sanchez — APPROVED** [review]
Looks and works as expected ✨ 

Played in brazil, Europe and local just fine 🚀

**Comment by Nico-Sanchez** [comment]
It doesn't work when custom IP is set. In main it works just fine.
Let's fix that, then we're ready to go 😄

**Review by Nico-Sanchez — CHANGES_REQUESTED** [review]
It doesn't work when custom IP is set. In main it works just fine.
Let's fix that, then we're ready to go 😄

**Comment by AngieDutra** [comment]
> It doesn't work when custom IP is set. In main it works just fine. Let's fix that, then we're ready to go 😄

Fixed it!

**Review by Nico-Sanchez — APPROVED** [review]

**Comment by Nico-Sanchez** [comment]
> > It doesn't work when custom IP is set. In main it works just fine. Let's fix that, then we're ready to go 😄
> 
> Fixed it!

Nice work! Looks fine with every server option, and the UI looks much better! ✨

**Review by agustinesco — APPROVED** [review]
LGTM!

**Pull request merged**
