### PR TITLE
Valtimer basic

### PR DESCRIPTION
**Pull request by BertovDev**
## Motivation

Implement valtimer basic with the backend, animations and vfx.

PR to test with -> https://github.com/lambdaclass/mirra_backend/pull/349

## Summary of changes

Adjust vfx, animation and projectile.
## How has this been tested?

To test it correctly in the config change   to "activation_delay_ms": 700,  in antimatter.
PIck valtimer use the basic.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by AngieDutra** [comment]
Back end [PR](https://github.com/lambdaclass/mirra_backend/pull/303) for this is already in main

**Review by AngieDutra — CHANGES_REQUESTED** [review]
If you don't mind it would be useful in the future to have a reference video to check if the vfx looks how it's supposed to or not.

Luckly I found this reference sent by the vfx team

https://github.com/lambdaclass/curse_of_mirra/assets/82987608/6f347f21-f30e-4077-a1d7-7ec17a59e344

This is how I see the animation:

https://github.com/lambdaclass/curse_of_mirra/assets/82987608/9846df96-3b48-46de-b35a-4d5f2ad17cd7

Therefore I believe there have been some issues to be fixed in the following areas:
- The hand trail is missing
- The collide of the orbe is missing
- The orbes seems to be missing it's trail

If I got something wrong or if there's any error on my part while testing please do say so 😊 

In addition, I have a question: If the testing process requieres a config change, how come there is no backend PR open for that? I saw a backend [PR](https://github.com/lambdaclass/mirra_backend/pull/303) for valtimer's basic and assumed this suggested change to test was already applied but I checked and it isn't. My question is why

**Comment by BertovDev** [comment]
> If you don't mind it would be useful in the future to have a reference video to check if the vfx looks how it's supposed to or not.
> 
> Luckly I found this reference sent by the vfx team
> Grabacion.de.pantalla.2024-03-05.a.la.s.11.04.07.mov
> 
> This is how I see the animation:
> Basic.animation.mov
> 
> Therefore I believe there have been some issues to be fixed in the following areas:
> 
>     * The hand trail is missing
> 
>     * The collide feedback of the orbe is missing
> 
>     * The orbe seems to be missing it's trail
> 
> 
> If I got something wrong or if there's any error on my part while testing please do say so 😊
> 
> In addition, I have a question: If the testing process requieres a config change, how come there is no backend PR open for that? I saw a backend [PR](https://github.com/lambdaclass/mirra_backend/pull/303) for valtimer's basic and assumed this suggested change to test was already applied but I checked and it isn't. My question is why

Nice and you are testing in the wrong place. Test it in the real game battle scnee. It should look like this:

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/90442316-9a09-4242-8aa3-79acf2162494

And about the backend you are right. Here is the PR with the config changes. https://github.com/lambdaclass/mirra_backend/pull/349

**Review by AngieDutra — CHANGES_REQUESTED** [review]
I believe there are some delays and transitions not working for a spam of the basic skill of valtimer. There is a bug for the vfx and animations if they are triggered with more that 1 stamina. This doesn't happen if the stamina is in 0 and 1 stamina is loaded during the spam

https://github.com/lambdaclass/curse_of_mirra/assets/82987608/2698ac86-a792-4087-bcaa-828444a76af8

**Review by agustinesco — APPROVED** [review]
LGTM! tested on the unity client and in an android release

**Review by AngieDutra — COMMENTED** [review]
I still don't see the vfx and animation as one. It's a timing and progesion issue. For reference:

Here are some frames from the reference video the vfx team sent
Captura de pantalla 2024-03-07 a las 17 54 02 p  m
Captura de pantalla 2024-03-07 a las 17 54 09 p  m

And this is how it's looking now:
Captura de pantalla 2024-03-07 a las 17 55 06 p  m

**Comment by BertovDev** [comment]
> I still don't see the vfx and animation as one. It's a timing and progesion issue. For reference:
> 
> Here are some frames from the reference video the vfx team sent Captura de pantalla 2024-03-07 a las 17 54 02 p  m Captura de pantalla 2024-03-07 a las 17 54 09 p  m
> 
> And this is how it's looking now: Captura de pantalla 2024-03-07 a las 17 55 06 p  m

I changed some values and now it looks like this, IGNORE THE PROJECTILE.

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/00a4d624-a2f1-4374-9e75-9f1ae7674c8e

What do you think?

**Comment by AngieDutra** [comment]
> > I still don't see the vfx and animation as one. It's a timing and progesion issue. For reference:
> > Here are some frames from the reference video the vfx team sent Captura de pantalla 2024-03-07 a las 17 54 02 p  m Captura de pantalla 2024-03-07 a las 17 54 09 p  m
> > And this is how it's looking now: Captura de pantalla 2024-03-07 a las 17 55 06 p  m
> 
> I changed some values and now it looks like this, IGNORE THE PROJECTILE.
> 
>  Screen.Recording.2024-03-07.at.18.17.26.mov 
> What do you think?

Looks just righ! *ignoring the projectile*

**Review by AngieDutra — COMMENTED** [review]
The first time I used the basic looked awesome. If I quickly press again the basic it looks like this:
Captura de pantalla 2024-03-07 a la(s) 18 40 55

**Review by AngieDutra — APPROVED** [review]
Awesome! ✨ Tested on Android too

**Review by agustinesco — APPROVED** [review]
🪨

**Pull request merged**
