### PR TITLE
Reduce volume

### LINKED ISSUE #1066: [FEATURE] Reduce default music/sounds volume
## 🚀 Feature
Ditto. A value between 0.5 and 0.7 may be better.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1066 

## Motivation

Reduce volumen, recreate the issue made in 
https://github.com/lambdaclass/curse_of_mirra/commit/8563a30dab64fdd978377b637d73b5bbfbb00b97

## Summary of changes

Create vars for volume.

## How has this been tested?

The volumen should be lower.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by agustinesco — CHANGES_REQUESTED** [review]
the volumed is reduced now but i think i've found a bug, when you enter a match and reduce the volume to 0 this is not persisted when you exit the match and you can hear the music the icon from the main screen is muted tho, this error is not present on main
i recorded the steps but i couldn't record audio 😅 

Uploading Screen Recording 2024-03-13 at 11.33.52.mov…

**Comment by BertovDev** [comment]
> the volumed is reduced now but i think i've found a bug, when you enter a match and reduce the volume to 0 this is not persisted when you exit the match and you can hear the music the icon from the main screen is muted tho, this error is not present on main i recorded the steps but i couldn't record audio 😅
> Screen.Recording.2024-03-13.at.11.33.52.mov

Nicee catch, fixed!

**Review by agustinesco — APPROVED** [review]
LGTM!

**Review by AngieDutra — CHANGES_REQUESTED** [review]
I've found an issue here that is not in main. Muted the sound in main screen, then started a match and although the sound does not play the toggles and sliders in settings are wrong. Again, this issue is not in main

**Comment by saugon** [comment]
There is another minor bug:

1. Enter a match and change the volume (It's better if you make a noticeable change to it)
2. Back on the main screen, mute and then unmute: the volume returns to the initial value instead of the one I set.

**Comment by BertovDev** [comment]
> I've found an issue here that is not in main. Muted the sound in main screen, then started a match and although the sound does not play the toggles and sliders in settings are wrong. Again, this issue is not in main

I replicated what you said and could not find the problem

https://github.com/lambdaclass/curse_of_mirra/assets/62818001/f827ffc6-8df7-459e-bdb1-daeee41133ce

**Comment by BertovDev** [comment]
> There is another minor bug:
> 
>     1. Enter a match and change the volume (It's better if you make a noticeable change to it)
> 
>     2. Back on the main screen, mute and then unmute: the volume returns to the initial value instead of the one I set.

Done!

**Review by AngieDutra — CHANGES_REQUESTED** [review]
I found the following issues:
- start mutes then go to game and the sfx show as 100 level but I can't listen to them. After using toggles this gets fixed but is not expected behavior
- Then I press exit (musics muted). In main then I unmute the music and I can no longer hear the music. (last settings in battle were muted).

**Comment by AngieDutra** [comment]
Also, the volume still feels a bit low

**Comment by BertovDev** [comment]
> start mutes then go to game and the sfx show as 100 level but I can't listen to them. After using toggles this gets fixed but is not expected behavior


> Also, the volume still feels a bit low

What about now?

**Comment by BertovDev** [comment]
> Then I press exit (musics muted). In main then I unmute the music and I can no longer hear the music. (last settings in battle were muted).

Nice catch, already fixed

**Comment by BertovDev** [comment]
> start mutes then go to game and the sfx show as 100 level but I can't listen to them. After using toggles this gets fixed but is not expected behavior

This is a behavior we already have in main and when it was implemented it was supposed to work that way. I agree we have to change it and it would be better if it take place in this issue: https://github.com/lambdaclass/curse_of_mirra/issues/1600

**Comment by AngieDutra** [comment]
Awesome! Will review now

**Comment by AngieDutra** [comment]
This PR needs main merge updated to test properly. Otherwise the match won't go through
Captura de pantalla 2024-03-19 a la(s) 5 35 59 p  m

**Review by AngieDutra — APPROVED** [review]
Awesome! Tested on Android build and Unity desktop. Volume is good imo. I think it's subjective to the device and user but it's definitely better than in main

**Review by tkz00 — APPROVED** [review]
Works great!

**Pull request merged**
