### PR TITLE
Floor textures update

### PR DESCRIPTION
**Pull request by gergahn**
Closes #[issue]
 
Fixed Issues betweem the normal map, color map and emission map.

It has a more clean look

### CODE REVIEW

**Review by AngieDutra — APPROVED** [review]
✔️ The files are organized
✔️ Built in mobile and ir looked good (Samsung s23+)
✔️ Did a photo comparison which I believe it's helpful to have here with feedback:
- noticed improvements in the center of the map. The is still room for improvement
- didn't noticed as much improvements in the sides of the map or far away sections like rocks and lava of the floor
Still, LGTM and is totally an upgrade ✨ 

Main (focus on the middle left part of the screenshot or the right side shading of the sand)
Captura de pantalla 2024-02-27 a la(s) 12 15 34

This branch (focus on the middle left part of the screenshot or the right side shading of the sand)
Captura de pantalla 2024-02-27 a la(s) 12 17 40

mobile screen:
Screenshot_20240227_123508_client

**Comment by BertovDev** [comment]
@AngieDutra Can you provide a mobile screen of the lava part of the map, I am talking about this:

Screenshot 2024-02-27 at 14 58 33

**Comment by AngieDutra** [comment]
> @AngieDutra Can you provide a mobile screen of the lava part of the map, I am talking about this:
> 
> Screenshot 2024-02-27 at 14 58 33

Captura de pantalla 2024-02-27 a la(s) 12 17 32

**Review by BertovDev — APPROVED** [review]
Looking great.

**Pull request merged**
