### PR TITLE
Update araban map

### PR DESCRIPTION
**Pull request by AngieDutra**
## Motivation

The map needs a visual upgrade

## Summary of changes

This PR adds colliders and improves the remaining textures so we improve our visual quality in game

DISCLAIMER:
Our PM decided it was best to have this without a back PR or the walls. Therefore this PR is ready but missing:
- colliders in back
- spawn reposition of players in back
- new wall models

ATENTION:
The quality of the textures needs to be set by the build settings / player settings. This has been discussed and approved by our PM

FILE > BUILD SETTINGS
Screenshot 2024-04-24 at 17 03 07

PLAYER SETTINGS > PLAYER
Screenshot 2024-04-24 at 17 03 19

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [x] Tested in Android.

### CODE REVIEW

**Review by alfopisano — DISMISSED** [review]
Nice!! Tested on iOS build and everything seemed to work fine, it looks so much better now

**Comment by AngieDutra** [comment]
I'll wait for this [PR](https://github.com/lambdaclass/curse_of_mirra/pull/1717) to be merged and solve conflicts after since our priority is that one to be in main asap

**Review by BertovDev — CHANGES_REQUESTED** [review]
Awesome ! and all colliders should be tick as Static since their are not moving.

**Comment by AngieDutra** [comment]
True, I'll do it asap

**Review by BertovDev — DISMISSED** [review]

**Review by BertovDev — APPROVED** [review]

**Review by mgrunwaldt — APPROVED** [review]

**Pull request merged**
