### PR TITLE
Add power up feature

### PR DESCRIPTION
**Pull request by agustinesco**
Test with [#268](https://github.com/lambdaclass/mirra_backend/pull/268)

Part of [963](https://github.com/lambdaclass/curse_of_mirra/issues/963)

### CODE REVIEW

**Comment by BertovDev** [comment]
Added:

- New placeholder model and material
- New Script to manage the creation and destroy of the powerups.

**Comment by BertovDev** [comment]
TODO: Add powerup counter in each player

**Review by BertovDev — DISMISSED** [review]
LGTM

**Review by mgrunwaldt — APPROVED** [review]
LGTM!

**Pull request merged**
