### PR TITLE
VFX europe branch

### PR DESCRIPTION
**Pull request by AngieDutra**
## Motivation

The vfx for most animations need to be updated

## Summary of changes

This PR updates h4ck's vfx

## Test with
Backend [PR](https://github.com/lambdaclass/mirra_backend/pull/253)

To test the multishot drag the multishot prefab to the projectile reference in skill 1 scriptable object. This has already an [issue](https://github.com/lambdaclass/curse_of_mirra/issues/1417)

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by AngieDutra** [comment]
> We are not using the vfx they sent us for the multishot: here it is in gae https://github.com/lambdaclass/curse_of_mirra/assets/22064054/f65763ee-8747-43bf-b1e8-b8cd5cd8466f
> 
> And this is what I see they sent us:
> 
>  h4ckrexternal.mp4 
> Also: I see that if I am moving and then dash the walking animation continues, is this something that changed in this PR or it's something we have off from a previous commit?
> 
>  dash.mov

I tested both singleshot and multishot assigning the multishot prefab in the scriptable object for the singleshot skill. Until [this issue](https://github.com/lambdaclass/curse_of_mirra/issues/1417) is fixed the multishot projectile is not available to use

I will fix the dash right away

**Comment by mgrunwaldt** [comment]
> > We are not using the vfx they sent us for the multishot: here it is in gae https://github.com/lambdaclass/curse_of_mirra/assets/22064054/f65763ee-8747-43bf-b1e8-b8cd5cd8466f
> > And this is what I see they sent us:
> > h4ckrexternal.mp4
> > Also: I see that if I am moving and then dash the walking animation continues, is this something that changed in this PR or it's something we have off from a previous commit?
> > dash.mov
> 
> I tested both singleshot and multishot assigning the multishot prefab in the scriptable object for the singleshot skill. Until [this issue](https://github.com/lambdaclass/curse_of_mirra/issues/1417) is fixed the multishot projectile is not available to use
> 
> I will fix the dash right away

ok , so this means that until that issue is addressed we have to use the same projectile (and the same vfx) in both attacks?

**Review by mgrunwaldt — CHANGES_REQUESTED** [review]
Looks good, I would only change one thing: the skill indicator for the dash is too long, and that might feel confusing while using it because you don't know where it ends. I'd make sure that if I'm using it horizontally  I can see it finish. Also I'd make it thinner so it kind of represents the trajectory h4ck would go through
image

**Review by mgrunwaldt — APPROVED** [review]
LGTM!

**Comment by AngieDutra** [comment]
If this [PR](https://github.com/lambdaclass/curse_of_mirra/pull/1411) is merged before this one, uma needs to be enabled

**Review by mgrunwaldt — APPROVED** [review]
Looking great!!

**Comment by BertovDev** [comment]
Great!!!
https://github.com/lambdaclass/curse_of_mirra/issues/1423

**Review by BertovDev — APPROVED** [review]
Merged main and tested on Android S23 Working good!

**Pull request merged**
