### PR TITLE
Fix bold font asset

### LINKED ISSUE #1565: [BUG] Build texts are broken
## 🐛 Bug Report

We detected that some texts are not being displayed at all (iOS) or have a "glitch" problem (Android). Apparently all the cases are using the bold variable of SourceSans3.

### Steps to Reproduce

Start a match, then keep an eye on:
- player names in prepare for battle
- "match starts in" counter text
- resume game" button
- Killfeed player names
- Defeat text before the death splash apprears (will need 3 players in match to test this)

image (3)
IMG_3782
IMG_3784
IMG_3785

### PR DESCRIPTION
**Pull request by AngieDutra**
Closes #1565

## Motivation

We detected that some texts are not being displayed at all (iOS) or have a "glitch" problem (Android). Apparently all the cases are using the bold variable of SourceSans3.

## Summary of changes

Updated the font asset and replaced it in every scene and prefab used

## How has this been tested?

Check all texts in all screens and pop ups are showing

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [x] I have tested the changes in another devices.
  - [x] Tested in iOS.
  - [x] Tested in Android.

### CODE REVIEW

**Review by saugon — DISMISSED** [review]
Nice job! (tested in iOS)

**Review by agustinesco — DISMISSED** [review]
The texts are now working perfectly in android! i just have a concern about a spinner

The spinner from the looking for battle is no longer spinning on this pr, this is working on main:

This pr:

https://github.com/lambdaclass/curse_of_mirra/assets/106101218/3899c72a-af3e-4833-8862-6957da64dcfa

master:

https://github.com/lambdaclass/curse_of_mirra/assets/106101218/08dc3b74-ae4a-49ee-aa80-203e49a23c29

**Review by BertovDev — DISMISSED** [review]
Tested in Android s23, everything seems to be looking good. No glitched text and the loading spinner is working good.

Nice

**Review by BertovDev — APPROVED** [review]
Awesome!! tested on Android s23.

**Review by saugon — APPROVED** [review]
Nice! Tested on iOS.

**Pull request merged**
