### PR TITLE
Fix projectiles trail

### PR DESCRIPTION
**Pull request by BertovDev**
## Motivation

Projectile trail was bug.

## Summary of changes

Now instead of using the same trail for each projectile, it gets instantiate on each new shoot. So a brand new trail is used avoiding bugs.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by BertovDev** [comment]
https://github.com/lambdaclass/curse_of_mirra/assets/62818001/f33911ed-030d-4ea5-a38e-a9525cd579b3

**Comment by manucamejo** [comment]
@BertovDev I'm seeing some trail and I don't know if it's ok. What do you think?
image

**Comment by manucamejo** [comment]
Here is the video
Uploading Screen Recording 2024-02-19 at 20.26.57.mov…

**Review by mgrunwaldt — APPROVED** [review]
LGTM

**Review by manucamejo — APPROVED** [review]

**Pull request merged**
