### PR TITLE
Araban v6

### PR DESCRIPTION
**Pull request by gergahn**
Closes #[issue]

## Motivation

First Iteration of the new map

Explain why not how.

## Summary of changes

New map 3D model and new textures

List changes in code.

## How has this been tested?

Describe the steps you performed to test this PR.
Play the game, check limits and proportions.

## Test additions / changes

List tests added/updated.

## Checklist
- [ ] I have tested the changes locally.
- [ ] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Comment by mgrunwaldt** [comment]
For a v1 it looks good, but I am worried that there are many things to fix and I don't see an issue for them. For example:
Player's feet get under the floor
image
image
Borders look pixelated
image

Please, create these issues and then I can accept it, not before

**Comment by gergahn** [comment]
Pixelated borders Issue: 
https://github.com/lambdaclass/curse_of_mirra/issues/1421

Feet get under the center ring issue:
https://github.com/lambdaclass/curse_of_mirra/issues/1422

**Comment by BertovDev** [comment]
Looking grate, now i will make some build in the phone.

**Review by mgrunwaldt — APPROVED** [review]
Still some work to be done (see issues) but great work!

**Review by BertovDev — APPROVED** [review]
Looking good!

**Pull request merged**
