### PR TITLE
Add new  H4ck animation

### LINKED ISSUE #1625: [REFACTOR] Add new H4ck Ulti animation
## 🚧 Refactor

Add new h4ck Ulti animation

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1625 

## Motivation

Add new ulltimate animation

## Summary of changes

Remove old animation, add new animation.

## How has this been tested?

Describe the steps you performed to test this PR.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by agustinesco — APPROVED** [review]
LGTM! tested in the unity client and in an android build

**Review by AngieDutra — CHANGES_REQUESTED** [review]
The ulti works but it appears as if the dash animation got lost in the process. Tested in main and there it works fine

**Comment by BertovDev** [comment]
> The ulti works but it appears as if the dash animation got lost in the process. Tested in main and there it works fine

Done

**Review by AngieDutra — APPROVED** [review]
Tested in Android build and Unity desktop. All h4ck animations work.
Although, now the animation ends before than the actual projectile shooting does, I assume is a WIP and this is contemplated until the new skill and animations are done

**Review by agustinesco — APPROVED** [review]
LGTM!

**Pull request merged**
