### PR TITLE
[GH-1718] showcase skill animation

### LINKED ISSUE #1718: [FEATURE] Showcase skill animation on characterInfo
## 🚀 Feature

When you press an Skill show the Animation.

### PR DESCRIPTION
**Pull request by BertovDev**
Closes #1718 

## Motivation

When you press the skills in CharacterInfo the animation is shown. Now we want each animation to be interrupted by the next. So we are displaying the animation that is currently selected.

How this works:

- Plays the animation according the name of the button (BASIC, ULTIMATE, DASH)

## Summary of changes

- Change Animators
- Implement code for displaying Animators.

## How has this been tested?

Go to character info test every skill.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by mgrunwaldt — CHANGES_REQUESTED** [review]
Functionality test failed: muflus freezes after leap

**Comment by BertovDev** [comment]
> Functionality test failed: muflus freezes after leap

All done!

**Comment by mgrunwaldt** [comment]
Still the same bug 

https://github.com/lambdaclass/curse_of_mirra/assets/22064054/2cbcfcaa-5ea5-44b1-855d-e29a77ac20c9


Also, noticed that if you select a new skill while executing one then the new one never gets executed. We should solve this, mi idea would be to create a queue and excecute the animation of the second skill as soon as the first one is over.


https://github.com/lambdaclass/curse_of_mirra/assets/22064054/d068b5da-eb82-46d8-a896-a72e28dde680

**Review by alfopisano — CHANGES_REQUESTED** [review]
When testing on iOS build I encountered some problems with Valtimer. I could saw some animations but at some point it freezed ad the character was not being displayed anymore: 

https://github.com/lambdaclass/curse_of_mirra/assets/116388676/c18f176d-ebd8-4a30-9260-5d20742ffd2e

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on unity desktop and iOS build and the animations looked fine

**Review by alfopisano — CHANGES_REQUESTED** [review]
To dismiss previous approve

**Review by alfopisano — APPROVED** [review]
Nice!! Tested on iOS build and it works much better now 🙌

**Review by AngieDutra — APPROVED** [review]
Tested in Android build and everything works as expected

**Pull request merged**
