### PR TITLE
Add ultimate vfx for new ultimate mechanic

### PR DESCRIPTION
**Pull request by BertovDev**
## Motivation

H4ck ultimate is now a pool. so the vfx should be changed.

## Summary of changes

Handle  vfx in code and add new vfx asset to scriptableObject.

## How has this been tested?

Test with -> https://github.com/lambdaclass/mirra_backend/pull/444
Start a game with H4ck, use the ulti.

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by Nico-Sanchez — CHANGES_REQUESTED** [review]
Works really nice!
just a few comments:
1. The area of the skill in the front is bigger than the one in the backend. They must be the same.
2. The animation of the falling projectiles could be faster, it's hard to aim. (this is not mandatory, we can iterate it).
3. The auto-aim direction of this skill is not normalized. The skill is being cast in the farthest point.

**Comment by marco-paulucci** [comment]
hi! i've made some adjustments to the backend PR if you can adjust for those.

some additional notes (some pointed by Nico)
- area looks bigger than what the area effect is
- they take too long to appear (to be synced with back)
- maybe I would make the animation as a whole a bit less overwhelming (smaller gfx for example)

**Comment by BertovDev** [comment]
https://github.com/lambdaclass/curse_of_mirra/assets/62818001/a939d202-9066-4931-aef5-20faca7f1fae

Now it is looking like this, let me know.

**Comment by Nico-Sanchez** [comment]
I'll address my previous comments in this new review:
> The area of the skill in the front is bigger than the one in the backend. They must be the same.
They're the same now 🎉 

> The animation of the falling projectiles could be faster, it's hard to aim. (this is not mandatory, we can iterate it).
This improved a lot. Good job. 👍 

> The auto-aim direction of this skill is not normalized. The skill is being cast in the farthest point.
This will be fixed in a future PR. Issue -> https://github.com/lambdaclass/mirra_backend/issues/455

Just a minor fix and we're ready to go:
The "preview" area and the skill area aren't the same, the last one is bigger. You can see it here 👇 

https://github.com/lambdaclass/curse_of_mirra/assets/65268603/67c4b5b0-91b8-4676-bb2d-3a9e3ec55a1f

**Comment by BertovDev** [comment]
> I'll address my previous comments in this new review:
> 
> > The area of the skill in the front is bigger than the one in the backend. They must be the same.
> > They're the same now 🎉
> 
> > The animation of the falling projectiles could be faster, it's hard to aim. (this is not mandatory, we can iterate it).
> > This improved a lot. Good job. 👍
> 
> > The auto-aim direction of this skill is not normalized. The skill is being cast in the farthest point.
> > This will be fixed in a future PR. Issue -> [lambdaclass/mirra_backend#455](https://github.com/lambdaclass/mirra_backend/issues/455)
> 
> Just a minor fix and we're ready to go: The "preview" area and the skill area aren't the same, the last one is bigger. You can see it here 👇
> Screen.Recording.2024-04-09.at.2.50.56.PM.mov

Yep what happens here is that the indicator and the damage zone (not the vfx) do not correlate, so instead of showing an empty zone (outside the vfx) that deals damage but correlate the indicator I prefer to show the vfx in correlation with the damage but not with the indicator. 

This is a problem of scale we have to handle
ISSUE: https://github.com/lambdaclass/curse_of_mirra/issues/1665

**Review by Nico-Sanchez — APPROVED** [review]

**Review by AngieDutra — APPROVED** [review]
In my opinion the clones generated could be a Game Object child to keep the order in the scene. But it's looking awesome. Tested on Android build and works

**Pull request merged**
