### PR TITLE
Modify position representations from integers to floats

### PR DESCRIPTION
**Pull request by AminArria**
## Summary of changes

This is a reboot of #1217  because the merge conflicts got too complicated to fix and to reduce the scope a bit

This PR modify the different integer types use to represent position related things to a float (f32 in Rust)

## How has this been tested?

Tested locally with backend PR https://github.com/lambdaclass/game_backend/pull/114

## Test additions / changes

List tests added/updated.

## Checklist
- [x] I have tested the changes locally.
- [x] I self-reviewed the changes on GitHub, line by line.
- [ ] Tests have been added/updated.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.
- [ ] I have tested the changes in another devices.
  - [ ] Tested in iOS.
  - [ ] Tested in Android.

### CODE REVIEW

**Review by ncontinanza — CHANGES_REQUESTED** [review]
I see you made changes in the messages.proto, but there are no changes in Messages.pb.cs, maybe you forgot to regenerate this file?

**Comment by AminArria** [comment]
@ncontinanza I think you missed it because I can see in the diff in Github, at least the file in the list, the actual diff is not showed by default because of the size

**Comment by ncontinanza** [comment]
> @ncontinanza I think you missed it because I can see in the diff in Github, at least the file in the list, the actual diff is not showed by default because of the size

Sorry, my bad

**Review by ncontinanza — APPROVED** [review]

**Comment by AminArria** [comment]
No longer relevant

**Pull request closed without merging**
